apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: members
build:
  artifacts:
    - image: gcr.io/daisyduck-reborn/members
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - config/dev/application.deployment.yaml
