spring:
  application:
    name: members
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:root@cluster0.vwpz2pv.mongodb.net/members_db?retryWrites=true&w=majority}
      database: members_db
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS} | %-20.20thread | %highlight(%-5level) | %magenta(%-25.25logger{25}) | %12(ID: %8mdc{CorrelationId}) | %m%n"