apiVersion: v1
kind: Service
metadata:
  name: members
spec:
  selector:
    app: members
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: members-config
data:
 uri: mongodb+srv://admin:root@cluster0.vwpz2pv.mongodb.net/members_db?retryWrites=true&w=majority
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: members
spec:
  replicas: 1
  selector:
    matchLabels:
      app: members
  template:
    metadata:
      labels:
        app: members
    spec:
      containers:
        - name: members
          image: gcr.io/daisyduck-reborn/members:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: members-config  
                  key: uri